services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "~/postgres_data:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASSWORD}
    ports:
      - "5050:80"
   
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_USER=
    ports:
      - "3306:3306"
    volumes:
      - "~/mysql_data:/var/lib/mysql"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:80"